pipeline {
    agent any


    stages {
        stage('Run Postman collections test') {
            steps {
                bat 'npm i -g newman'
                bat '"C:/Users/jinan/AppData/Roaming/npm/newman" run "%WORKSPACE%/Github_Integration_with_jenkins/Collection.json" --disable-unicode"'
            }
        }
    }

    post {
        always {
            emailext(
                subject: "${currentBuild.currentResult}: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: "<html><body><p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} #${env.BUILD_NUMBER}</a></p></body></html>",
                to: 'dora59906@gmail.com',
                from: 'jenkiBot',
                mimeType: 'text/html'
            )
        }
    }
}
